homeInfoParams:
    Title: "Unplugging From The Matrix"
    Content: Hey, it's [Anindya,Anindya Barua](/about). This blog is actually about my day to day life ,my likings and how i am trying to scape the reality So Hakuna Matata :)
    # ![Anindya Barua](/img/avatar-circle.webp)