homeInfoParams:
    Title: "কিংকর্তব্যবিমূঢ় আইলসাপ্রধান এর জগত"
    Content: হাই! আমি অনিন্দ্য, অনিন্দ্য বড়ুয়া! (/about) ।  কিংকর্তব্যবিমূঢ় আইলসাপ্রধান এর জগতে আপনাকে স্বাগতম। আমার জীবন,পছন্দ এবং প্রতিনিয়তই নিজেকে পরিবর্তনের বিষয় নিয়েই এই ব্লগ লেখা। আপনার দিন শুভ হোক :)

socialIcons:
        - name: telegram
          url: "https://t.me/fahimscirex"    
        - name: twitter
          url: "https://twitter.com/fahimscirex"
        - name: mastodon
          url: "https://fosstodon.org/web/accounts/313800"
        - name: github
          url: "https://github.com/fahimscirex"
        - name: goodreads
          url: "https://goodreads.com/fahimscirex"
        - name: rss
          url: "/bn/rss.xml"